---
services:
  postgresql-db:
    image: postgres:17
    platform: linux/amd64
    hostname: postgresql-db
    ports: [5432:5432]
    volumes: [./data/postgres:/var/lib/postgresql/data]
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -q']
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports: [5450:80]
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@xyz.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on: [postgresql-db]
  redis:
    image: redis:latest
    platform: linux/amd64
    ports: [6379:6379]
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 5s
      timeout: 3s
      retries: 5
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports: [5540:5540]
    depends_on: [redis]
  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    container_name: redis-ui
    ports: [7843:7843]
    volumes: [./data/p3x-redis-ui:/settings]
    depends_on: [redis]
  api-server:
    hostname: ${API_SERVICE_HOST}
    image: wire-api
    build:
      context: .
      dockerfile: services/api/server/Dockerfile
      target: development
      args:
        BUILDKIT_INLINE_CACHE: 1
        VERSION: local
    ports: ['${API_SERVICE_PORT}:${API_SERVICE_PORT}']
    platform: linux/arm64
    depends_on:
      redis:
        condition: service_healthy
      postgresql-db:
        condition: service_started
    mem_limit: 6gb
    volumes:
      - ./:/app
      - cargo-cache:/app/target
      - cargo-registry:/usr/local/cargo/registry
    environment:
      - RUST_LOG=${RUST_LOG}
      - LOG_FORMAT=pretty
      - API_SERVICE_PORT=${API_SERVICE_PORT}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_CREDENTIALS=${DATABASE_CREDENTIALS}
      - DATABASE_RW_ENDPOINT=postgresql-db
      - DATABASE_RO_ENDPOINT=postgresql-db
      # xls file path
      - ENERGY_READINGS_XLS_FILE_PATH=${ENERGY_READINGS_XLS_FILE_PATH}
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports: [9187:9187]
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      postgresql-db:
        condition: service_healthy
  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports: [9121:9121]
    environment: [REDIS_ADDR=redis://redis:6379]
    depends_on:
      redis:
        condition: service_healthy
  prometheus-pushgateway:
    image: prom/pushgateway
    restart: always
    ports: [9091:9091]
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    entrypoint: [/etc/prometheus/setup.sh]
    extra_hosts: [host.docker.internal:host-gateway]
    environment:
      - MONITOR_PW=${MONITORING_PASSWORD}
      - API_METRICS_TARGET=${API_METRICS_TARGET}
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/web-config.yml:/etc/prometheus/web-config.yml
      - ./scripts/prometheus-setup.sh:/etc/prometheus/setup.sh
      - prometheus_data:/prometheus
    ports: [9090:9090]
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes: [/proc:/host/proc:ro, /sys:/host/sys:ro, /:/rootfs:ro]
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports: [9100:9100]
    depends_on: [prometheus]
    deploy:
      mode: global
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports: [8080:8080]
    depends_on: [prometheus]
    deploy:
      mode: global
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    volumes: [./monitoring/alertmanager/:/etc/alertmanager/]
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/alertmanager
    depends_on: [prometheus]
    ports: [9093:9093]
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: [3000:3000]
    env_file: [.env]
    depends_on: [grafana-image-renderer]
    environment:
      - GF_PROVISIONING_ENABLED_ENV_SUBST=true
      - GF_METRICS_BASIC_AUTH_USERNAME=${MONITORING_USER}
      - GF_METRICS_BASIC_AUTH_PASSWORD=${MONITORING_PASSWORD}
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
  grafana-image-renderer:
    image: grafana/grafana-image-renderer
    container_name: grafana-image-renderer
    restart: always
volumes:
  cargo-cache:
  cargo-registry:
  prometheus_data:
  grafana_data:
