global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-server'
    static_configs:
      - targets: ['${API_METRICS_TARGET}']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    basic_auth:
      username: 'admin'
      password_file: '/etc/prometheus/metrics_pw.txt'

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
    basic_auth:
      username: 'admin'
      password_file: '/etc/prometheus/metrics_pw.txt'

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['prometheus-pushgateway:9091']
